version: '3.8'
services:
  ipmi-tools:
    image: ghcr.io/daiybh/ipmitools/ipmi-tools:main
    container_name: ipmi-app
    ports:
      - "5000:5000"
    volumes:
      - ./servers.json:/app/servers.json
    restart: unless-stopped